/*
 * Projeto de Gerenciamento de Cinema em Java
 * Programação Orientada a Objetos II
 * Professor Ivan Ricarte
 * Faculdade de Tecnologia - UNICAMP
 */
package view;

import control.ControleSessao;
import control.Resposta;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 * Esta classe é responsável pela interface de seleção de poltronas.
 * @author Daniel
 */
public class Poltronas extends javax.swing.JDialog {

    private int codSessao;
    private Resposta rp;
    String selecionada = "";
    
    /**
     * Creates new form Poltronas
     */
    public Poltronas(java.awt.Frame parent, boolean modal, String codSessao, Resposta rp) {
        super(parent, modal);
        initComponents();
        
        this.codSessao = Integer.parseInt(codSessao);
        this.rp = rp;
        
        List<JButton> buttonsPoltronas = new ArrayList<>();
        buttonsPoltronas.add(jButtonPoltrona1);
        buttonsPoltronas.add(jButtonPoltrona2);
        buttonsPoltronas.add(jButtonPoltrona3);
        buttonsPoltronas.add(jButtonPoltrona4);
        buttonsPoltronas.add(jButtonPoltrona5);
        buttonsPoltronas.add(jButtonPoltrona6);
        buttonsPoltronas.add(jButtonPoltrona7);
        buttonsPoltronas.add(jButtonPoltrona8);
        buttonsPoltronas.add(jButtonPoltrona9);
        buttonsPoltronas.add(jButtonPoltrona10);
        buttonsPoltronas.add(jButtonPoltrona11);
        buttonsPoltronas.add(jButtonPoltrona12);
        buttonsPoltronas.add(jButtonPoltrona13);
        buttonsPoltronas.add(jButtonPoltrona14);
        buttonsPoltronas.add(jButtonPoltrona15);
        buttonsPoltronas.add(jButtonPoltrona16);
        buttonsPoltronas.add(jButtonPoltrona17);
        buttonsPoltronas.add(jButtonPoltrona18);
        buttonsPoltronas.add(jButtonPoltrona19);
        buttonsPoltronas.add(jButtonPoltrona20);
        buttonsPoltronas.add(jButtonPoltrona21);
        buttonsPoltronas.add(jButtonPoltrona22);
        buttonsPoltronas.add(jButtonPoltrona23);
        buttonsPoltronas.add(jButtonPoltrona24);
        buttonsPoltronas.add(jButtonPoltrona25);
        buttonsPoltronas.add(jButtonPoltrona26);
        buttonsPoltronas.add(jButtonPoltrona27);
        buttonsPoltronas.add(jButtonPoltrona28);
        buttonsPoltronas.add(jButtonPoltrona29);
        buttonsPoltronas.add(jButtonPoltrona30);
        buttonsPoltronas.add(jButtonPoltrona31);
        buttonsPoltronas.add(jButtonPoltrona32);
        buttonsPoltronas.add(jButtonPoltrona33);
        buttonsPoltronas.add(jButtonPoltrona34);
        buttonsPoltronas.add(jButtonPoltrona35);
        buttonsPoltronas.add(jButtonPoltrona36);
        buttonsPoltronas.add(jButtonPoltrona37);
        buttonsPoltronas.add(jButtonPoltrona38);
        buttonsPoltronas.add(jButtonPoltrona39);
        buttonsPoltronas.add(jButtonPoltrona40);
        buttonsPoltronas.add(jButtonPoltrona41);
        buttonsPoltronas.add(jButtonPoltrona42);
        buttonsPoltronas.add(jButtonPoltrona43);
        buttonsPoltronas.add(jButtonPoltrona44);
        buttonsPoltronas.add(jButtonPoltrona45);
        buttonsPoltronas.add(jButtonPoltrona46);
        buttonsPoltronas.add(jButtonPoltrona47);
        buttonsPoltronas.add(jButtonPoltrona48);
        buttonsPoltronas.add(jButtonPoltrona49);
        buttonsPoltronas.add(jButtonPoltrona50);
        
        if(!rp.getMsg().equals(""))
            selecionada = rp.getMsg();
        
        int[] poltronas = ControleSessao.getPoltronas(this.codSessao);
        
        for(int i = 0; i < 50; i++){
            if(poltronas[i] == 0)
                buttonsPoltronas.get(i).setBackground(Color.green);
            if(poltronas[i] == 1)
                buttonsPoltronas.get(i).setBackground(Color.red);
            if((!selecionada.equals("")) && (i == (Integer.parseInt(selecionada))-1))
                buttonsPoltronas.get(i).setBackground(Color.blue);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelGVoltar = new javax.swing.JLabel();
        jLabelTela = new javax.swing.JLabel();
        jButtonPoltrona1 = new javax.swing.JButton();
        jButtonPoltrona11 = new javax.swing.JButton();
        jButtonPoltrona21 = new javax.swing.JButton();
        jButtonPoltrona31 = new javax.swing.JButton();
        jButtonPoltrona41 = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonPoltrona2 = new javax.swing.JButton();
        jButtonPoltrona3 = new javax.swing.JButton();
        jButtonPoltrona4 = new javax.swing.JButton();
        jButtonPoltrona5 = new javax.swing.JButton();
        jButtonPoltrona6 = new javax.swing.JButton();
        jButtonPoltrona7 = new javax.swing.JButton();
        jButtonPoltrona8 = new javax.swing.JButton();
        jButtonPoltrona9 = new javax.swing.JButton();
        jButtonPoltrona10 = new javax.swing.JButton();
        jButtonPoltrona12 = new javax.swing.JButton();
        jButtonPoltrona13 = new javax.swing.JButton();
        jButtonPoltrona14 = new javax.swing.JButton();
        jButtonPoltrona15 = new javax.swing.JButton();
        jButtonPoltrona16 = new javax.swing.JButton();
        jButtonPoltrona17 = new javax.swing.JButton();
        jButtonPoltrona18 = new javax.swing.JButton();
        jButtonPoltrona19 = new javax.swing.JButton();
        jButtonPoltrona20 = new javax.swing.JButton();
        jButtonPoltrona30 = new javax.swing.JButton();
        jButtonPoltrona29 = new javax.swing.JButton();
        jButtonPoltrona25 = new javax.swing.JButton();
        jButtonPoltrona22 = new javax.swing.JButton();
        jButtonPoltrona26 = new javax.swing.JButton();
        jButtonPoltrona23 = new javax.swing.JButton();
        jButtonPoltrona27 = new javax.swing.JButton();
        jButtonPoltrona28 = new javax.swing.JButton();
        jButtonPoltrona24 = new javax.swing.JButton();
        jButtonPoltrona35 = new javax.swing.JButton();
        jButtonPoltrona33 = new javax.swing.JButton();
        jButtonPoltrona37 = new javax.swing.JButton();
        jButtonPoltrona40 = new javax.swing.JButton();
        jButtonPoltrona32 = new javax.swing.JButton();
        jButtonPoltrona36 = new javax.swing.JButton();
        jButtonPoltrona38 = new javax.swing.JButton();
        jButtonPoltrona34 = new javax.swing.JButton();
        jButtonPoltrona39 = new javax.swing.JButton();
        jButtonPoltrona43 = new javax.swing.JButton();
        jButtonPoltrona47 = new javax.swing.JButton();
        jButtonPoltrona50 = new javax.swing.JButton();
        jButtonPoltrona44 = new javax.swing.JButton();
        jButtonPoltrona46 = new javax.swing.JButton();
        jButtonPoltrona48 = new javax.swing.JButton();
        jButtonPoltrona49 = new javax.swing.JButton();
        jButtonPoltrona45 = new javax.swing.JButton();
        jButtonPoltrona42 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Poltrona");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(159, 168, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Seleção de Poltrona");

        jLabelGVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jLabelGVoltar.setToolTipText("Voltar");
        jLabelGVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelGVoltarMouseReleased(evt);
            }
        });

        jLabelTela.setBackground(new java.awt.Color(102, 102, 102));
        jLabelTela.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelTela.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTela.setText("TELA");
        jLabelTela.setOpaque(true);

        jButtonPoltrona1.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona1.setText("1");
        jButtonPoltrona1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona1.setContentAreaFilled(false);
        jButtonPoltrona1.setFocusable(false);
        jButtonPoltrona1.setOpaque(true);
        jButtonPoltrona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona11.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona11.setText("11");
        jButtonPoltrona11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona11.setContentAreaFilled(false);
        jButtonPoltrona11.setFocusable(false);
        jButtonPoltrona11.setOpaque(true);
        jButtonPoltrona11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona21.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona21.setText("21");
        jButtonPoltrona21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona21.setContentAreaFilled(false);
        jButtonPoltrona21.setFocusable(false);
        jButtonPoltrona21.setOpaque(true);
        jButtonPoltrona21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona31.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona31.setText("31");
        jButtonPoltrona31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona31.setContentAreaFilled(false);
        jButtonPoltrona31.setFocusable(false);
        jButtonPoltrona31.setOpaque(true);
        jButtonPoltrona31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona41.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona41.setText("41");
        jButtonPoltrona41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona41.setContentAreaFilled(false);
        jButtonPoltrona41.setFocusable(false);
        jButtonPoltrona41.setOpaque(true);
        jButtonPoltrona41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setEnabled(false);
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonPoltrona2.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona2.setText("2");
        jButtonPoltrona2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona2.setContentAreaFilled(false);
        jButtonPoltrona2.setFocusable(false);
        jButtonPoltrona2.setOpaque(true);
        jButtonPoltrona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona3.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona3.setText("3");
        jButtonPoltrona3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona3.setContentAreaFilled(false);
        jButtonPoltrona3.setFocusable(false);
        jButtonPoltrona3.setOpaque(true);
        jButtonPoltrona3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona4.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona4.setText("4");
        jButtonPoltrona4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona4.setContentAreaFilled(false);
        jButtonPoltrona4.setFocusable(false);
        jButtonPoltrona4.setOpaque(true);
        jButtonPoltrona4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona5.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona5.setText("5");
        jButtonPoltrona5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona5.setContentAreaFilled(false);
        jButtonPoltrona5.setFocusable(false);
        jButtonPoltrona5.setOpaque(true);
        jButtonPoltrona5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona6.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona6.setText("6");
        jButtonPoltrona6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona6.setContentAreaFilled(false);
        jButtonPoltrona6.setFocusable(false);
        jButtonPoltrona6.setOpaque(true);
        jButtonPoltrona6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona7.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona7.setText("7");
        jButtonPoltrona7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona7.setContentAreaFilled(false);
        jButtonPoltrona7.setFocusable(false);
        jButtonPoltrona7.setOpaque(true);
        jButtonPoltrona7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona8.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona8.setText("8");
        jButtonPoltrona8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona8.setContentAreaFilled(false);
        jButtonPoltrona8.setFocusable(false);
        jButtonPoltrona8.setOpaque(true);
        jButtonPoltrona8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona9.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona9.setText("9");
        jButtonPoltrona9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona9.setContentAreaFilled(false);
        jButtonPoltrona9.setFocusable(false);
        jButtonPoltrona9.setOpaque(true);
        jButtonPoltrona9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona10.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona10.setText("10");
        jButtonPoltrona10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona10.setContentAreaFilled(false);
        jButtonPoltrona10.setFocusable(false);
        jButtonPoltrona10.setOpaque(true);
        jButtonPoltrona10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona12.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona12.setText("12");
        jButtonPoltrona12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona12.setContentAreaFilled(false);
        jButtonPoltrona12.setFocusable(false);
        jButtonPoltrona12.setOpaque(true);
        jButtonPoltrona12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona13.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona13.setText("13");
        jButtonPoltrona13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona13.setContentAreaFilled(false);
        jButtonPoltrona13.setFocusable(false);
        jButtonPoltrona13.setOpaque(true);
        jButtonPoltrona13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona14.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona14.setText("14");
        jButtonPoltrona14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona14.setContentAreaFilled(false);
        jButtonPoltrona14.setFocusable(false);
        jButtonPoltrona14.setOpaque(true);
        jButtonPoltrona14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona15.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona15.setText("15");
        jButtonPoltrona15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona15.setContentAreaFilled(false);
        jButtonPoltrona15.setFocusable(false);
        jButtonPoltrona15.setOpaque(true);
        jButtonPoltrona15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona16.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona16.setText("16");
        jButtonPoltrona16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona16.setContentAreaFilled(false);
        jButtonPoltrona16.setFocusable(false);
        jButtonPoltrona16.setOpaque(true);
        jButtonPoltrona16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona17.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona17.setText("17");
        jButtonPoltrona17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona17.setContentAreaFilled(false);
        jButtonPoltrona17.setFocusable(false);
        jButtonPoltrona17.setOpaque(true);
        jButtonPoltrona17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona18.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona18.setText("18");
        jButtonPoltrona18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona18.setContentAreaFilled(false);
        jButtonPoltrona18.setFocusable(false);
        jButtonPoltrona18.setOpaque(true);
        jButtonPoltrona18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona19.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona19.setText("19");
        jButtonPoltrona19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona19.setContentAreaFilled(false);
        jButtonPoltrona19.setFocusable(false);
        jButtonPoltrona19.setOpaque(true);
        jButtonPoltrona19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona20.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona20.setText("20");
        jButtonPoltrona20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona20.setContentAreaFilled(false);
        jButtonPoltrona20.setFocusable(false);
        jButtonPoltrona20.setOpaque(true);
        jButtonPoltrona20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona30.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona30.setText("30");
        jButtonPoltrona30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona30.setContentAreaFilled(false);
        jButtonPoltrona30.setFocusable(false);
        jButtonPoltrona30.setOpaque(true);
        jButtonPoltrona30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona29.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona29.setText("29");
        jButtonPoltrona29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona29.setContentAreaFilled(false);
        jButtonPoltrona29.setFocusable(false);
        jButtonPoltrona29.setOpaque(true);
        jButtonPoltrona29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona25.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona25.setText("25");
        jButtonPoltrona25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona25.setContentAreaFilled(false);
        jButtonPoltrona25.setFocusable(false);
        jButtonPoltrona25.setOpaque(true);
        jButtonPoltrona25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona22.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona22.setText("22");
        jButtonPoltrona22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona22.setContentAreaFilled(false);
        jButtonPoltrona22.setFocusable(false);
        jButtonPoltrona22.setOpaque(true);
        jButtonPoltrona22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona26.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona26.setText("26");
        jButtonPoltrona26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona26.setContentAreaFilled(false);
        jButtonPoltrona26.setFocusable(false);
        jButtonPoltrona26.setOpaque(true);
        jButtonPoltrona26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona23.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona23.setText("23");
        jButtonPoltrona23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona23.setContentAreaFilled(false);
        jButtonPoltrona23.setFocusable(false);
        jButtonPoltrona23.setOpaque(true);
        jButtonPoltrona23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona27.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona27.setText("27");
        jButtonPoltrona27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona27.setContentAreaFilled(false);
        jButtonPoltrona27.setFocusable(false);
        jButtonPoltrona27.setOpaque(true);
        jButtonPoltrona27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona28.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona28.setText("28");
        jButtonPoltrona28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona28.setContentAreaFilled(false);
        jButtonPoltrona28.setFocusable(false);
        jButtonPoltrona28.setOpaque(true);
        jButtonPoltrona28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona24.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona24.setText("24");
        jButtonPoltrona24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona24.setContentAreaFilled(false);
        jButtonPoltrona24.setFocusable(false);
        jButtonPoltrona24.setOpaque(true);
        jButtonPoltrona24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona35.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona35.setText("35");
        jButtonPoltrona35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona35.setContentAreaFilled(false);
        jButtonPoltrona35.setFocusable(false);
        jButtonPoltrona35.setOpaque(true);
        jButtonPoltrona35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona33.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona33.setText("33");
        jButtonPoltrona33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona33.setContentAreaFilled(false);
        jButtonPoltrona33.setFocusable(false);
        jButtonPoltrona33.setOpaque(true);
        jButtonPoltrona33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona37.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona37.setText("37");
        jButtonPoltrona37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona37.setContentAreaFilled(false);
        jButtonPoltrona37.setFocusable(false);
        jButtonPoltrona37.setOpaque(true);
        jButtonPoltrona37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona40.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona40.setText("40");
        jButtonPoltrona40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona40.setContentAreaFilled(false);
        jButtonPoltrona40.setFocusable(false);
        jButtonPoltrona40.setOpaque(true);
        jButtonPoltrona40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona32.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona32.setText("32");
        jButtonPoltrona32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona32.setContentAreaFilled(false);
        jButtonPoltrona32.setFocusable(false);
        jButtonPoltrona32.setOpaque(true);
        jButtonPoltrona32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona36.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona36.setText("36");
        jButtonPoltrona36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona36.setContentAreaFilled(false);
        jButtonPoltrona36.setFocusable(false);
        jButtonPoltrona36.setOpaque(true);
        jButtonPoltrona36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona38.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona38.setText("38");
        jButtonPoltrona38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona38.setContentAreaFilled(false);
        jButtonPoltrona38.setFocusable(false);
        jButtonPoltrona38.setOpaque(true);
        jButtonPoltrona38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona34.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona34.setText("34");
        jButtonPoltrona34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona34.setContentAreaFilled(false);
        jButtonPoltrona34.setFocusable(false);
        jButtonPoltrona34.setOpaque(true);
        jButtonPoltrona34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona39.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona39.setText("39");
        jButtonPoltrona39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona39.setContentAreaFilled(false);
        jButtonPoltrona39.setFocusable(false);
        jButtonPoltrona39.setOpaque(true);
        jButtonPoltrona39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona43.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona43.setText("43");
        jButtonPoltrona43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona43.setContentAreaFilled(false);
        jButtonPoltrona43.setFocusable(false);
        jButtonPoltrona43.setOpaque(true);
        jButtonPoltrona43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona47.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona47.setText("47");
        jButtonPoltrona47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona47.setContentAreaFilled(false);
        jButtonPoltrona47.setFocusable(false);
        jButtonPoltrona47.setOpaque(true);
        jButtonPoltrona47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona50.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona50.setText("50");
        jButtonPoltrona50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona50.setContentAreaFilled(false);
        jButtonPoltrona50.setFocusable(false);
        jButtonPoltrona50.setOpaque(true);
        jButtonPoltrona50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona44.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona44.setText("44");
        jButtonPoltrona44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona44.setContentAreaFilled(false);
        jButtonPoltrona44.setFocusable(false);
        jButtonPoltrona44.setOpaque(true);
        jButtonPoltrona44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona46.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona46.setText("46");
        jButtonPoltrona46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona46.setContentAreaFilled(false);
        jButtonPoltrona46.setFocusable(false);
        jButtonPoltrona46.setOpaque(true);
        jButtonPoltrona46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona48.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona48.setText("48");
        jButtonPoltrona48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona48.setContentAreaFilled(false);
        jButtonPoltrona48.setFocusable(false);
        jButtonPoltrona48.setOpaque(true);
        jButtonPoltrona48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona49.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona49.setText("49");
        jButtonPoltrona49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona49.setContentAreaFilled(false);
        jButtonPoltrona49.setFocusable(false);
        jButtonPoltrona49.setOpaque(true);
        jButtonPoltrona49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona45.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona45.setText("45");
        jButtonPoltrona45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona45.setContentAreaFilled(false);
        jButtonPoltrona45.setFocusable(false);
        jButtonPoltrona45.setOpaque(true);
        jButtonPoltrona45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        jButtonPoltrona42.setBackground(new java.awt.Color(0, 255, 0));
        jButtonPoltrona42.setText("42");
        jButtonPoltrona42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPoltrona42.setContentAreaFilled(false);
        jButtonPoltrona42.setFocusable(false);
        jButtonPoltrona42.setOpaque(true);
        jButtonPoltrona42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoltronaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonPoltrona31, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonPoltrona41, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona32, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona42, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPoltrona14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPoltrona15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPoltrona16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona46, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPoltrona17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPoltrona18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPoltrona19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonPoltrona9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoltrona10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPoltrona20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonPoltrona50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabelGVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabelTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonPoltrona2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonPoltrona1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonPoltrona12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonPoltrona11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonPoltrona22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonPoltrona21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonPoltrona32, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonPoltrona31, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonPoltrona42, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonPoltrona41, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonPoltrona3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButtonPoltrona13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPoltrona23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPoltrona33, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPoltrona43, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonPoltrona4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(jButtonPoltrona14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPoltrona24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPoltrona34, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPoltrona44, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonPoltrona6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jButtonPoltrona16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPoltrona26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPoltrona36, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPoltrona46, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonPoltrona7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(jButtonPoltrona17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona37, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona47, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonPoltrona8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(jButtonPoltrona18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona28, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona38, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona48, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jButtonPoltrona19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona39, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPoltrona49, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPoltrona10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoltrona9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jButtonPoltrona20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPoltrona30, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPoltrona40, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPoltrona50, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPoltrona5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButtonPoltrona15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPoltrona25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPoltrona35, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPoltrona45, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(570, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        rp.setMsg(selecionada);
        this.dispose();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonPoltronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPoltronaActionPerformed
        JButton sel = (JButton) evt.getSource();
        
        if(selecionada.equals("") || (selecionada.equals(sel.getText()))){           
            if(sel.getBackground().toString().equals(Color.green.toString())){ //Marca poltrona
                sel.setBackground(Color.blue);
                selecionada = sel.getText();
                jButtonConfirmar.setEnabled(true);
            }
            else if(sel.getBackground().toString().equals(Color.blue.toString())){ //Desmarca poltrona
                sel.setBackground(Color.green);
                selecionada = "";
                jButtonConfirmar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButtonPoltronaActionPerformed

    private void jLabelGVoltarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGVoltarMouseReleased
        this.dispose();
    }//GEN-LAST:event_jLabelGVoltarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poltronas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poltronas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poltronas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poltronas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Poltronas dialog = new Poltronas(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonPoltrona1;
    private javax.swing.JButton jButtonPoltrona10;
    private javax.swing.JButton jButtonPoltrona11;
    private javax.swing.JButton jButtonPoltrona12;
    private javax.swing.JButton jButtonPoltrona13;
    private javax.swing.JButton jButtonPoltrona14;
    private javax.swing.JButton jButtonPoltrona15;
    private javax.swing.JButton jButtonPoltrona16;
    private javax.swing.JButton jButtonPoltrona17;
    private javax.swing.JButton jButtonPoltrona18;
    private javax.swing.JButton jButtonPoltrona19;
    private javax.swing.JButton jButtonPoltrona2;
    private javax.swing.JButton jButtonPoltrona20;
    private javax.swing.JButton jButtonPoltrona21;
    private javax.swing.JButton jButtonPoltrona22;
    private javax.swing.JButton jButtonPoltrona23;
    private javax.swing.JButton jButtonPoltrona24;
    private javax.swing.JButton jButtonPoltrona25;
    private javax.swing.JButton jButtonPoltrona26;
    private javax.swing.JButton jButtonPoltrona27;
    private javax.swing.JButton jButtonPoltrona28;
    private javax.swing.JButton jButtonPoltrona29;
    private javax.swing.JButton jButtonPoltrona3;
    private javax.swing.JButton jButtonPoltrona30;
    private javax.swing.JButton jButtonPoltrona31;
    private javax.swing.JButton jButtonPoltrona32;
    private javax.swing.JButton jButtonPoltrona33;
    private javax.swing.JButton jButtonPoltrona34;
    private javax.swing.JButton jButtonPoltrona35;
    private javax.swing.JButton jButtonPoltrona36;
    private javax.swing.JButton jButtonPoltrona37;
    private javax.swing.JButton jButtonPoltrona38;
    private javax.swing.JButton jButtonPoltrona39;
    private javax.swing.JButton jButtonPoltrona4;
    private javax.swing.JButton jButtonPoltrona40;
    private javax.swing.JButton jButtonPoltrona41;
    private javax.swing.JButton jButtonPoltrona42;
    private javax.swing.JButton jButtonPoltrona43;
    private javax.swing.JButton jButtonPoltrona44;
    private javax.swing.JButton jButtonPoltrona45;
    private javax.swing.JButton jButtonPoltrona46;
    private javax.swing.JButton jButtonPoltrona47;
    private javax.swing.JButton jButtonPoltrona48;
    private javax.swing.JButton jButtonPoltrona49;
    private javax.swing.JButton jButtonPoltrona5;
    private javax.swing.JButton jButtonPoltrona50;
    private javax.swing.JButton jButtonPoltrona6;
    private javax.swing.JButton jButtonPoltrona7;
    private javax.swing.JButton jButtonPoltrona8;
    private javax.swing.JButton jButtonPoltrona9;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGVoltar;
    private javax.swing.JLabel jLabelTela;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
